# Generated by Django 4.0.1 on 2022-01-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_author_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='nameAuthor',
        ),
    ]
