# Generated by Django 4.0.1 on 2022-01-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_alter_author_id_alter_book_nameauthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='nameAuthor',
            new_name='id_author',
        ),
    ]
